#!/bin/python

import math
import os
import random
import re
import sys

from collections import Counter

# Complete the gameOfThrones function below.
def gameOfThrones(s):
    d = dict(Counter(s))
    odd_count = 0
    for letter_count in d.values():
        if letter_count % 2 != 0:
            odd_count += 1
    if odd_count > 1:
        return 'NO'
    else:
        return 'YES'


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = raw_input()

    result = gameOfThrones(s)

    fptr.write(result + '\n')

    fptr.close()
