#!/bin/python

import math
import os
import random
import re
import sys

# Complete the pangrams function below.
def pangrams(s):
    s = set(s.lower())
    s.discard(" ")
    return "pangram" if len(s) == 26 else "not pangram"    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = raw_input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
